---
title: "EpiModel2"
author: "Saipranav Avula"
date: "7/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(sna)
library(tsna)
library(ndtv)
library(ergm)
library(htmlwidgets)
library(EpiModel)
event <- read.csv("~/Documents/GitHub/IDEA-COVID-ContactTracing/final_data/EVENT.csv", stringsAsFactors=FALSE)
schedule <- read.csv("~/Documents/GitHub/IDEA-COVID-ContactTracing/final_data/SCHEDULE.csv", stringsAsFactors=FALSE)
attends <- read.csv("~/Documents/GitHub/IDEA-COVID-ContactTracing/final_data/ATTENDS.csv", stringsAsFactors=FALSE)
person <- read.csv("~/Documents/GitHub/IDEA-COVID-ContactTracing/final_data/PERSON.csv", stringsAsFactors=FALSE)
location <- read.csv("~/Documents/GitHub/IDEA-COVID-ContactTracing/final_data/LOCATION.csv", stringsAsFactors=FALSE)
contacts <- read.csv("~/Documents/GitHub/IDEA-COVID-ContactTracing/final_data/CONTACTS.csv", stringsAsFactors=FALSE)
```


```{r}
set.seed(2001)
selected_stu <- sample_n(person,225)
selected_stu
links <- contacts %>%
  filter(PersonID1 %in% selected_stu$PersonID & PersonID2 %in% selected_stu$PersonID & PersonID1 != PersonID2) %>%
  select(-Type) %>%
  arrange(Date, StartTime)
links <- links %>%
  filter(Date == 1) 

start <- links %>%
  gather(key = "link", value = "id", PersonID1, PersonID2) %>%
  select(StartTime, id) %>%
  group_by(id) %>%
  filter(StartTime == min(StartTime)) %>%
  unique()
end <- links %>%
  gather(key = "link", value = "id", PersonID1, PersonID2) %>%
  select(EndTime, id) %>%
  group_by(id) %>%
  filter(EndTime == max(EndTime)) %>%
  unique()
start
end
selected_stu <- left_join(start,end,by=("id"))[c(1,3,2)]
selected_stu$numid <- as.numeric(seq(nrow(selected_stu)))
selected_stu
links$head <- match(links$PersonID1, selected_stu$id)
links$tail <- match(links$PersonID2, selected_stu$id)
links


```
```{r}
selected_stu[,c(1,2,4)]
links[,c(4,5,6,7)]
nw <- network(links[,c(6,7)], directed = FALSE)
nw
epidyn <- networkDynamic(nw, edge.spells = links[,c(4,5,6,7)], vertex.spells = as.matrix(selected_stu[,c(1,2,4)]))
```
```{r}
net.init.mod <- function(x, param, init, control, s) {
  
  # Master Data List
  dat <- list()
  dat$param <- param
  dat$init <- init
  dat$control <- control
  
  dat$attr <- list()
  dat$stats <- list()
  dat$temp <- list()
  
  # Network Parameters
  dat$nw <- x
  dat$param$modes <- 1
  
  
  # Initialization
  
  ## Infection Status and Time Modules
  n <- network.size(dat$nw)
  dat$attr$status <- rep("s", n)
  dat$attr$status[sample(1:n, init$i.num)] <- "i"
  
  dat$attr$active <- rep(1, n)
  dat$attr$entrTime <- rep(800, n)
  dat$attr$exitTime <- rep(NA, n)
  
  dat$attr$infTime <- rep(NA, n)
  dat$attr$infTime[dat$attr$status == "i"] <- 800
  
  #--------------- --------------------------------Create dynamic attribute // for the infected at the initial step
  idsInf <- which(dat$attr$active == 1 & dat$attr$status == "i")
  dat$nw <- activate.vertex.attribute(dat$nw, "testatus", value = "i", onset = 1, terminus = Inf, v = idsInf) 
  
  
  ## Get initial prevalence
  dat <- get_prev.net(dat, at = 1)
  return(dat)
}

```
```{r}
my.inf.mod <- function(dat, at) {
  
  ## Variables ##
  active <- dat$attr$active
  status <- dat$attr$status
  
  inf.prob <- dat$param$inf.prob
  act.rate <- dat$param$act.rate
  
  nw <- dat$nw
  
  # Vector of infected and susceptible IDs
  idsSus <- which(active == 1 & status == "s")
  idsInf <- which(active == 1 & status == "i")
  nActive <- sum(active == 1)
  nElig <- length(idsInf)
  
  
  # Initialize vectors
  nInf <- totInf <- 0
  
  ## Processes ##
  # If some infected AND some susceptible, then proceed
  if (nElig > 0 && nElig < nActive) {
    
    # Get discordant edgelist
    del <- discord_edgelist(dat, at)
    
    # If some discordant edges, then proceed
    if (!(is.null(del))) {
      
      # Infection probabilities
      del$transProb <- inf.prob
      
      # Act rates
      del$actRate <- act.rate
      
      # Calculate final transmission probability per timestep
      del$finalProb <- 1 - (1 - del$transProb) ^ del$actRate
      
      # Randomize transmissions and subset df
      transmit <- rbinom(nrow(del), 1, del$finalProb)
      del <- del[which(transmit == 1), ]
      
      # Set new infections vector
      idsNewInf <- unique(del$sus)
      totInf <- length(idsNewInf) 
      
      
      
      # Update attributes
      if (totInf > 0) {
        
        dat$attr$status[idsNewInf] <- "i"
        dat$attr$infTime[idsNewInf] <- at 
        
        
        #---------------------------------------------------------update dynamic attribute // for the new infected
        activate.vertex.attribute(nw, "testatus", value = "i", onset = at, terminus = Inf, v = idsNewInf) 
      }
      
    } 
  } 
  
  ## Summary statistics ##
  if (at == 2) {
    dat$epi$si.flow <- c(0, totInf)
  } else {
    dat$epi$si.flow[at] <- totInf
  }
  
  dat$nw <- nw
  return(dat)
}

```
```{r}
inf_prob <- 0.1
ini.num <- 1


param <- param.net(inf.prob = inf_prob)  
init <- init.net(i.num = ini.num) 
control <- control.net(type = "SI", nsteps = 1800, nsims = 1,    # nsteps = 17377
                       initialize.FUN = net.init.mod, infection.FUN = my.inf.mod,
                       module.order = c("infection.FUN" , "get_prev.FUN"),  #
                       skip.check = TRUE, save.nwstats = F, save.network = T)

sim <- netsim(epidyn, param, init,control)
```
```{r}
plot(sim, main = "Prevalence", xlim = c(800,1800), ylim = c(0,225))
plot(sim, ylim=c(0, 0.2), y = "si.flow", xlim = c(800,1800), main = "Incidence")
par(mar = c(1,1,1,1), mfrow = c(2, 2))
plot(sim, type = "network", col.status = TRUE, at = 800, sims = 1, main="8 AM")
plot(sim, type = "network", col.status = TRUE, at = 1200, sims = 1, main="12 PM")
plot(sim, type = "network", col.status = TRUE, at = 1400, sims = 1, main="2 PM")
plot(sim, type = "network", col.status = TRUE, at = 1600, sims = 1, main="4 PM")
```